### ISSUE TITLE
Save and Cancel button positions for Box Cover, Notebook Cover, and Diary Cover

### ISSUE THREAD

**Issue by ShihChinYang** [bsafes/bsafes-web#14]
![Box Cover](http://www.imareader.com/bsafes/boxCover.jpeg)
![Notebook Cover](http://www.imareader.com/bsafes/notebookCover.jpeg)
![Diary Cover](http://www.imareader.com/bsafes/diaryCover.jpeg)
Please check if #13 also solves this issue. If not, please fix.

**Comment by abid-2362** [comment]
#13 does not solves this issue automatically, because each page has different class names for their containers.
To solve this issue, we need to check for multiple classes to get the width of the container right in calculation of the value of "right" css property.
