### ISSUE TITLE
Making workspace activities collapsable for the same item

### ISSUE THREAD

**Issue by ShihChinYang** [bsafes/bsafes-web#16]
![Workspace activities](http://www.imareader.com/bsafes/workspaceActivities.png)
Description:
Every workspace keeps its own history of activities. Activities list what have been done to items in a workspace. For a series of activities on the same item, we want to make them collapsable. In the following screen shot, we want to see one Mercedes Benz box first, expandable to 2 Mercedes Benz boxes, and collapsable to 1 Mercedes Benz again.  
![Collapsable activities](http://www.imareader.com/bsafes/collapseActivities.png)
Likewise, we want to see one Honda box, expandable to 4 Honda boxes, and collapsable to 1 Honda again.  
And so on for subsequent activities.

Solution:
1. Adding a expand/collapse button to the bottom of the first activity box of a series of activity boxes for the same item when there are more than 1 continuous activities for the same item.
2. Using  font awesome 4.0(already included)  fa-caret-down for expanding button
3. Using fa-caret-up for collapse button
4. When clicking on expand button, all activity boxes following would be displayed with animation.
5. When clicking on collapse, those activity boxes would collapsed to display the first one only.
6. At the bottom of the activities list, there is a more button which would list more activities when clicked. Note the top more activities have to be collapsed to the bottom activity boxes of previous list if they are for the same item.

**Comment by ShihChinYang** [comment]
For a new team workspace, after creation of first page, there should be 1 activity, but activities view is empty.

**Comment by abid-2362** [comment]
@ShihChinYang I have fixed the issue and have sent a PR to fix this.

**Comment by ShihChinYang** [comment]
Fixed .
