### ISSUE TITLE
Allowing a user to upload images before the completion of downloading all images

### ISSUE THREAD

**Issue by ShihChinYang** [bsafes/bsafes-web#70]
Currently, in the gallery, the upload-image button doesn't show up until all images are downloaded. Please change the code to allow uploading images before the completion of downloading all images.

**Comment by ShihChinYang** [comment]
Implemented and tested.

**Comment by ShihChinYang** [comment]
$downloadImage = $('.uploadImageTemplate').clone().removeClass('uploadImageTemplate hidden').addClass('downloadImage');
Why above change in pageControls.js?

**Comment by anthonyyang87** [comment]
Added fix. Now that line of code is:

$downloadImage = $('.downloadImageTemplate').clone().removeClass('downloadImageTemplate uploadImageTemplate hidden').addClass('downloadImage');

**Comment by ShihChinYang** [comment]
Implemented and tested.
